name = "OscarPolytope"
uuid = "61a3517e-1e29-11e9-1fd3-4d098866440e"
authors = ["Taylor Brysiewicz <taylor.brysiewicz@mis.mpg.de>","Michael Joswig <joswig@math.tu-berlin.de>","Marek Kaluba <kalmar@amu.edu.pl>","Sascha Timme <sascha.timme@googlemail.com>","Claus Fieker <fieker@mathematik.uni-kl.de>", "Sebastian Gutsche <gutsche@momo.math.rwth-aachen.de>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
